image:
  tag: 2.2.1-3

ingress:
  hosts:
    - deb.openswitch.net

api:
  ingress:
    hosts:
      - aptly.openswitch.net
    tls:
    - secretName: aptly-openswitch-net
      hosts:
        - aptly.openswitch.net

