alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    fqdn: "alerts.opx.openswitch.net"
    tls:
      - secretName: alertmanager-general-tls
        hosts:
          - alerts.opx.openswitch.net
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    fqdn: "prometheus.opx.openswitch.net"
    tls:
      - secretName: prometheus-k8s-tls
        hosts:
          - prometheus.opx.openswitch.net
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi

grafana:
  adminPassword: "YourPass123#"
  auth:
    anonymous:
      enabled: "false"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    fqdn: "monitoring.opx.openswitch.net"
    tls:
      - secretName: grafana-tls
        hosts:
          - monitoring.opx.openswitch.net
  storageSpec:
    class: gp2
    accessMode: "ReadWriteOnce"
    resources:
      requests:
        storage: 50Gi

# default rules are in templates/general.rules.yaml
# prometheusRules: {}

# Select Deployed DNS Solution
deployCoreDNS: false
deployKubeDNS: true
