{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "aptly.fullname" . -}}
{{- $name := include "aptly.name" . -}}
{{- $servicePort := .Values.api.port -}}
{{- $ingressPath := .Values.api.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "aptly-api"
  labels:
    app: {{ template "aptly.name" . }}
    chart: {{ template "aptly.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.api.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.api.ingress.tls }}
  tls:
  {{- range .Values.api.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $name }}
              servicePort: 8080
  {{- end }}
{{- end }}
