apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aptly.fullname" . }}
  labels:
    app: {{ template "aptly.name" . }}
    chart: {{ template "aptly.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key: {{ .Values.aptly.key | b64enc | quote }}

