#!/bin/bash

cat <<EOF
Welcome to Aptly!

Preinstalled aliases
---------------
* list - aptly list all repos, snapshots, mirrors, and publishes
* graph_aptly - aptly graph with basic html wrapper, check http://127.0.0.1/apt.svg

Environment variables
---------------------
* PUB - default publish location, filesystem:public:

EOF

export PUB="filesystem:public:"

list() {
aptly repo list
echo '----------------------------------------------------------------------'
aptly snapshot list
echo '----------------------------------------------------------------------'
aptly mirror list
echo '----------------------------------------------------------------------'
aptly publish list
}

graph_aptly() {
curl -s http://localhost:8080/api/graph.svg?layout=vertical \
  >/usr/share/nginx/html/apt.svg
}

build_graph() {
  debtree -b --no-versions opx-dell-vm | gvpr -i 'N[name == "*opx*"]' | dot -Tsvg -o /usr/share/nginx/html/build-unstable.svg
}

dep_graph() {
  debtree --no-versions opx-dell-vm | gvpr -i 'N[name == "*opx*"]' | dot -Tsvg -o /usr/share/nginx/html/dep-unstable.svg
}

