#!/bin/bash

cat <<EOF
Welcome to Aptly!

Preinstalled aliases
---------------
* list - aptly list all repos, snapshots, mirrors, and publishes
* repo_graph - aptly graph, check http://127.0.0.1/apt.(svg|png)

Environment variables
---------------------
* PUB - default publish location, filesystem:public:

EOF

export PUB="filesystem:public:"

list() {
aptly repo list
echo '----------------------------------------------------------------------'
aptly snapshot list
echo '----------------------------------------------------------------------'
aptly mirror list
echo '----------------------------------------------------------------------'
aptly publish list
}

repo_graph() {
  curl -s http://localhost:8080/api/graph.svg?layout=vertical \
    >/usr/share/nginx/html/apt.svg

  curl -s http://localhost:8080/api/graph.png?layout=vertical \
    >/usr/share/nginx/html/apt.png
}

dep_graph() {
  debtree -b --no-versions opx-pas \
  | gvpr -i 'N[name == "*opx*"]' \
  | dot -Tsvg -o /usr/share/nginx/html/build-unstable.svg

  debtree --no-versions opx-dell-vm \
  | gvpr -i 'N[name == "*opx*"]' \
  | dot -Tsvg -o /usr/share/nginx/html/dep-unstable.svg
}

